# Generated by Django 4.1.4 on 2022-12-10 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='admin',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='doctor',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='registration',
            name='patient',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
