# Generated by Django 4.1.4 on 2022-12-10 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0003_remove_registration_email_remove_registration_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registration',
        ),
    ]
