# Generated by Django 4.1.4 on 2022-12-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0006_remove_customer_admin_remove_customer_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pharmecy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=250)),
            ],
        ),
    ]
