# Generated by Django 4.1.4 on 2022-12-12 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0008_pharmecy_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmecy',
            name='image',
            field=models.ImageField(null=True, upload_to='permecy'),
        ),
    ]
