# Generated by Django 4.1.4 on 2022-12-14 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0009_alter_pharmecy_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=20)),
                ('phone', models.PositiveIntegerField()),
                ('address', models.TextField(max_length=300)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
