# Generated by Django 4.1.4 on 2022-12-14 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0010_payment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EditProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=300)),
                ('workingPlace', models.TextField(max_length=300)),
                ('exprience', models.PositiveIntegerField()),
                ('Price', models.PositiveIntegerField()),
                ('profile_pic', models.ImageField(upload_to='profile')),
            ],
        ),
    ]
