# Generated by Django 4.1.4 on 2022-12-14 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0012_specialist'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='special_doctor')),
                ('name', models.CharField(max_length=100)),
                ('desp', models.TextField(max_length=200)),
                ('workplace', models.CharField(max_length=200)),
                ('exprience', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
