# Generated by Django 4.1.4 on 2022-12-17 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0013_doctordetails'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EditProfile',
        ),
    ]
