# Generated by Django 4.1.4 on 2022-12-19 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0014_delete_editprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableAppoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('available', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=30)),
                ('number', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='DoctorAppoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('hospital_name', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=200)),
                ('place', models.CharField(max_length=200)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ViewProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='doctor_profile')),
                ('name', models.CharField(max_length=200)),
                ('designation', models.CharField(max_length=200)),
                ('specialization_area', models.CharField(max_length=200)),
                ('department', models.CharField(max_length=200)),
                ('hospital', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=200)),
                ('education', models.TextField(max_length=500)),
                ('training', models.TextField(max_length=500)),
                ('research', models.TextField(max_length=500)),
            ],
        ),
    ]
