# Generated by Django 4.1.4 on 2022-12-19 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0015_availableappoint_booking_doctorappoint_viewprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctorappoint',
            name='pic',
            field=models.ImageField(null=True, upload_to='doc'),
        ),
    ]
