# Generated by Django 4.1.4 on 2022-12-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0017_delete_viewprofile_doctorappoint_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctorappoint',
            name='hospital',
        ),
        migrations.RemoveField(
            model_name='doctorappoint',
            name='location',
        ),
    ]
