# Generated by Django 4.1.4 on 2022-12-20 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0018_remove_doctorappoint_hospital_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availableappoint',
            name='price',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
