# Generated by Django 4.1.4 on 2022-12-20 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0019_availableappoint_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Confirm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card', models.PositiveIntegerField()),
                ('expire', models.TextField()),
                ('cvc', models.PositiveIntegerField()),
                ('country', models.CharField(max_length=200)),
            ],
        ),
    ]
