# Generated by Django 4.1.4 on 2022-12-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0021_emergency'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergency',
            name='img',
            field=models.ImageField(null=True, upload_to='emergency'),
        ),
    ]
