# Generated by Django 4.1.4 on 2022-12-20 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0022_emergency_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergency',
            name='img',
        ),
    ]
