# Generated by Django 4.1.4 on 2022-12-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0024_ambulancedetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='ambulancedetails',
            name='car_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
