# Generated by Django 4.1.4 on 2022-12-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0025_ambulancedetails_car_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.TextField()),
                ('number', models.PositiveIntegerField()),
                ('blood', models.TextField()),
                ('age', models.PositiveIntegerField()),
            ],
        ),
    ]
