# Generated by Django 4.1.4 on 2022-12-23 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0027_remove_payment_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='total',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
