# Generated by Django 4.1.4 on 2022-12-23 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0028_payment_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='total',
            field=models.IntegerField(null=True),
        ),
    ]
