# Generated by Django 4.1.4 on 2022-12-23 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0030_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
