# Generated by Django 4.1.4 on 2022-12-23 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0031_blog_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='text',
            field=models.TextField(null=True),
        ),
    ]
