# Generated by Django 4.1.4 on 2022-12-25 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saveline', '0032_blog_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctordetails',
            name='profession',
            field=models.CharField(choices=[('food', 'food'), ('child', 'child'), ('nurologist', 'nurologist'), ('medicine', 'medicine')], max_length=50, null=True),
        ),
    ]
